from django.urls import path, include

from . import views
from rest_framework import routers

app_name = 'tanksapi'

router = routers.DefaultRouter()
# the names for the urls are auto generated by the router, following
# http://www.django-rest-framework.org/api-guide/routers/#defaultrouter
router.register('maps', views.MapViewSet)


urlpatterns = [
    path('', include(router.urls)),
]